# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: wedding

# SEO
marketing:
  seo:
    site_type: Personal
    local_business_type: ''
    org_name: ''
    description: 'Wedding website for Leah Selman and Jacob Haimes.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: false
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    # button:
    #   enable: true
    #   text: "RSVP"
    #   url: "GOOGLE FORM LINK"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  blox: "sitemap"
  content:
    logo:
      text: "LEAH SELMAN AND JACOB HAIMES"
    tagline: "WEDDING MOMENT"
  design:
    columns: 4
  copyright:
    # notice: '© {year}'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Extensions
extensions:
  convertkit:
    # To use the ConvertKit Newsletter blox, provide your public API Key from your ConvertKit account settings page
    api_key: ""

# Security
hugoblox:
  security:
    csp:
      policy: ""
      report_only: false
    frame_options: allow                 # deny | sameorigin | allow - allow enables iframe embedding
    permissions_policy: ""

i_am_a_sponsor: true
